galxe_oat_v2_response = {
    "id": "galxe-oat-v2",
    "contract_address": "0x5d666f215a85b87cb042d59662a7ecd2c8cc44e6",
    "asset_platform_id": "polygon-pos",
    "name": "Galaxy OAT",
    "symbol": "OAT",
    "image": {
        "small": "https://assets.coingecko.com/nft_contracts/images/2912/small/galxe-oat-v2.png?1675752596"
    },
    "description": "Galxe OAT (On-chain Achievement Token) is a digital badge standard on Polygon and BNB Chain to "
                   "record your on-chain and off-chain life experiences. Co-launched by Galxe, Polygon Studios, "
                   "and NFT Storage by Filecoin and IPFS.",
    "native_currency": "ethereum",
    "native_currency_symbol": "ETH",
    "floor_price": {
        "native_currency": 8.9,
        "usd": 20944
    },
    "market_cap": {
        "native_currency": 206821266,
        "usd": 486499267384
    },
    "volume_24h": {
        "native_currency": 0.00305302,
        "usd": 7.18
    },
    "floor_price_in_usd_24h_percentage_change": 97.1627,
    "floor_price_24h_percentage_change": {
        "usd": 97.16270304511663,
        "native_currency": 85.49811494752596
    },
    "market_cap_24h_percentage_change": {
        "usd": 97.1627030451176,
        "native_currency": 86.28203335683946
    },
    "volume_24h_percentage_change": {
        "usd": -52.46163165187622,
        "native_currency": -51.6070077144563
    },
    "number_of_unique_addresses": 2148806,
    "number_of_unique_addresses_24h_percentage_change": 0.05094,
    "volume_in_usd_24h_percentage_change": -52.46163,
    "total_supply": 23228603,
    "one_day_sales": 55,
    "one_day_sales_24h_percentage_change": -24.6575342465753,
    "one_day_average_sale_price": 0.00005550940022,
    "one_day_average_sale_price_24h_percentage_change": -35.7693011482784,
    "links": {
        "homepage": "https://galxe.com",
        "twitter": "https://twitter.com/",
        "discord": "https://discord.gg/galxe"
    },
    "floor_price_7d_percentage_change": {
        "usd": 2639.4714872655672,
        "native_currency": 2434.995176326485
    },
    "floor_price_14d_percentage_change": {
        "usd": 949889975.4268028,
        "native_currency": 888462949.7644345
    },
    "floor_price_30d_percentage_change": {
        "usd": 688099853.763397,
        "native_currency": 604643001.3482833
    },
    "floor_price_60d_percentage_change": {
        "usd": 716547827.5282918,
        "native_currency": 542349546.5371346
    },
    "floor_price_1y_percentage_change": {
        "usd": 414271388.6586531,
        "native_currency": 294891877.4391015
    },
    "explorers": [
        {
            "name": "Polygonscan",
            "link": "https://polygonscan.com/token/0x5d666f215a85b87cb042d59662a7ecd2c8cc44e6"
        }
    ]
}

cryptopunks_response = {
    "id": "cryptopunks",
    "contract_address": "0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB",
    "asset_platform_id": "ethereum",
    "name": "CryptoPunks",
    "symbol": "PUNK",
    "image": {
        "small": "https://assets.coingecko.com/nft_contracts/images/270/small/cryptopunks.png?1681893032"
    },
    "description": "<h3 dir=\"ltr\">What Is the CryptoPunks NFT Collection?</h3>\r\n\r\n<p dir=\"ltr\">CryptoPunks is "
                   "an Ethereum-based NFT collection of 10,000 unique art characters. Out of the 10,000 Punks "
                   "&ndash;&nbsp;there are 6,039 males, 3,840 females, 88 zombies, 24 apes, and 9 alien punks. Due to "
                   "their rarity, the zombie, ape, and alien punks are priced&nbsp;significantly "
                   "higher.</p>\r\n\r\n<p dir=\"ltr\">The CryptoPunks collection is one of the earliest and most "
                   "popular collections in the NFT space, with some high-profile celebrities owning their own Punk. "
                   "Some of these celebrities include Serena Williams, Logan Paul, Mark Cuban, and SnoopDogg. The "
                   "CryptoPunks NFT collection was so highly sought after by art collectors that they were even sold "
                   "at Sotheby&#39;s and Christie&#39;s, which are international auction houses.&nbsp;</p>\r\n\r\n<p "
                   "dir=\"ltr\">Launched in June 2017, 9,000 of the 10,000 NFTs were free for mint, while the other "
                   "remaining 1,000 NFTs were held by Larva Labs. Four years later, by 2021, the same NFTs were sold "
                   "for millions of dollars.&nbsp;</p>\r\n\r\n<p dir=\"ltr\">The CryptoPunks NFT collection was "
                   "algorithmically generated by a pixelated character generator that assigned each individual "
                   "character their unique traits. The algorithm ensures that no two NFTs in the collection are the "
                   "same, making each of them unique. Generally speaking, the CryptoPunks that do not have many "
                   "unique features have a lower floor price.</p>\r\n\r\n<h3 dir=\"ltr\">Who Is the Team Behind "
                   "CryptoPunks?</h3>\r\n\r\n<p dir=\"ltr\">The NFT collection was actually released as an experiment "
                   "by two Canadian software developers from Larva Labs studio. At the time of the release, "
                   "the ERC-721 token standard did not exist, and the two software developers, Matt Hall&nbsp;and "
                   "John Watkinson, released the CryptoPunks collection as an experiment as custom contract "
                   "NFTs.&nbsp;</p>\r\n\r\n<p dir=\"ltr\">According to the team, the CryptoPunks collection drew "
                   "inspiration from the 1970s London Punk scene, the sci-fi cyberpunk movement, the popular movie "
                   "Blade Runner, and the book Neuromancer.</p>\r\n\r\n<p dir=\"ltr\">In 2022, the team behind Bored "
                   "Ape Yacht Club NFT, Yuga Labs, acquired CryptoPunks along with <a "
                   "href=\"https://www.coingecko.com/en/nft/meebits\" target=\"_blank\">Meebits</a>, another popular "
                   "NFT collection. Now that they own three of the most popular NFT collections in the NFT space, "
                   "Yuga Labs has established itself as a big player in the NFT space.&nbsp;</p>\r\n\r\n<h3 "
                   "dir=\"ltr\">What Is the Utility of the CryptoPunks Collection?</h3>\r\n\r\n<p dir=\"ltr\">Being a "
                   "holder of the CryptoPunks NFT collection gives holders exclusive access to member-only events "
                   "where users are required to hold a CryptoPunk NFT to participate. This helps holders to interact "
                   "with other holders and get access to new features. Having been one of the pioneers in the NFT "
                   "space, the CryptoPunks collection has built up a pretty strong sense of community. As such, "
                   "some holders actually purchase the CryptoPunks NFT to gain access to the community and new "
                   "releases.&nbsp;</p>\r\n\r\n<p dir=\"ltr\">As the CrytoPunks collection is one of the most iconic "
                   "and popular in the NFT space, the CryptoPunk NFTs are also often regarded as a symbol of prestige "
                   "and wealth. Therefore, oftentimes many owners of the CryptoPunks NFT collection will use their "
                   "NFT as their profile picture or avatar on social media.</p>\r\n\r\n<p dir=\"ltr\">Some of the "
                   "owners will also <a href=\"https://decrypt.co/77872/cryptopunk-owners-have-new-way-make-money"
                   "-renting-out-their-avatars\" rel=\"nofollow noopener\" target=\"_blank\">rent their NFTs</a> out "
                   "or use their CryptoPunks collection as collateral to <a "
                   "href=\"https://www.coingecko.com/learn/blur-and-blend-nft-marketplace\" target=\"_blank\">borrow "
                   "ETH</a>. This is part of Blur&rsquo;s lending program, Blend, where users are able to borrow and "
                   "lend NFTs through a peer-to-peer platform.&nbsp;</p>\r\n\r\n<p dir=\"ltr\">As the NFT space "
                   "continues to grow, it is likely that the utility of the NFT collection will continue to "
                   "expand.</p>\r\n\r\n<h3 dir=\"ltr\">What makes CryptoPunks special?</h3>\r\n\r\n<p dir=\"ltr\">The "
                   "CryptoPunks collection is known for its culture significance in the history of Ethereum and NFT. "
                   "It is touted as the first <a href=\"https://www.coingecko.com/en/glossary/pfp\">PFP</a> project "
                   "and sometimes the first NFT collection that managed to retain its value.</p>\r\n\r\n<h3 "
                   "dir=\"ltr\">Wrapped CryptoPunks&nbsp;</h3>\r\n\r\n<p dir=\"ltr\">The Wrapped CryptoPunks NFT "
                   "collection is a derivative of the original CryptoPunks NFT collection. As mentioned earlier, "
                   "the CryptoPunks NFT collections are made on a custom contract. This means that they are only "
                   "available to be traded on the Ethereum chain.&nbsp;</p>\r\n\r\n<p dir=\"ltr\">When you wrap your "
                   "CryptoPunk, it is essentially changing your NFT to an ERC-721 token standard, which is currently "
                   "used to power most of the NFTs we see today. This allows your wrapped CryptoPunks to be used in "
                   "other decentralized applications besides Ethereum.&nbsp;</p>\r\n\r\n<p dir=\"ltr\">The wrapping "
                   "process is reversible, and NFT holders are able to wrap and unwrap their CryptoPunks at will. "
                   "However, it is important to note that the process to wrap the CryptoPunks NFT includes "
                   "interacting with smart contracts via etherscan.io and that failure to complete all the steps "
                   "correctly can result in a loss of the NFT.&nbsp;</p>\r\n",
    "native_currency": "ethereum",
    "native_currency_symbol": "ETH",
    "floor_price": {
        "native_currency": 55.7,
        "usd": 131052
    },
    "market_cap": {
        "native_currency": 556666,
        "usd": 1309735408
    },
    "volume_24h": {
        "native_currency": 277,
        "usd": 651732
    },
    "floor_price_in_usd_24h_percentage_change": 6.17156,
    "floor_price_24h_percentage_change": {
        "usd": 6.171562161336516,
        "native_currency": -0.07176175098672408
    },
    "market_cap_24h_percentage_change": {
        "usd": 6.171562161336371,
        "native_currency": -0.07176175098672408
    },
    "volume_24h_percentage_change": {
        "usd": 393.80272924818854,
        "native_currency": 364.76510067114094
    },
    "number_of_unique_addresses": "null",
    "number_of_unique_addresses_24h_percentage_change": 0,
    "volume_in_usd_24h_percentage_change": 393.80273,
    "total_supply": 9994,
    "one_day_sales": 3,
    "one_day_sales_24h_percentage_change": 200,
    "one_day_average_sale_price": 92.33333333333333,
    "one_day_average_sale_price_24h_percentage_change": 54.9217002237136,
    "links": {
        "homepage": "https://cryptopunks.app/",
        "twitter": "https://twitter.com/cryptopunksnfts",
        "discord": "https://discord.gg/tQp4pSE"
    },
    "floor_price_7d_percentage_change": {
        "usd": 11.203374057163549,
        "native_currency": 3.148148148148148
    },
    "floor_price_14d_percentage_change": {
        "usd": 7.095329143784573,
        "native_currency": 0.36036036036036034
    },
    "floor_price_30d_percentage_change": {
        "usd": 12.229988145071818,
        "native_currency": -1.4159292035398232
    },
    "floor_price_60d_percentage_change": {
        "usd": 64.1337424550669,
        "native_currency": 24.46927374301676
    },
    "floor_price_1y_percentage_change": {
        "usd": 71.60916796782213,
        "native_currency": -10.305958132045088
    },
    "explorers": [
        {
            "name": "Etherscan",
            "link": "https://etherscan.io/token/0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB"
        },
        {
            "name": "Ethplorer",
            "link": "https://ethplorer.io/address/0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB"
        }
    ]
}

cometh_spaceships_response = {
    "id": "cometh-spaceships",
    "contract_address": "0xbcd4f1ecff4318e7a0c791c7728f3830db506c71",
    "asset_platform_id": "ethereum",
    "name": "Cometh Spaceships",
    "symbol": "SPACESHIP",
    "image": {
        "small": "https://assets.coingecko.com/nft_contracts/images/245/small/unnamed.png?1642315798"
    },
    "description": "Cometh is a DeFi powered game with yield generating NFT. Get spaceships, explore the galaxy and "
                   "earn tokens.",
    "native_currency": "ethereum",
    "native_currency_symbol": "ETH",
    "floor_price": {
        "native_currency": 35,
        "usd": 82245
    },
    "market_cap": {
        "native_currency": 429380,
        "usd": 1008981146
    },
    "volume_24h": {
        "native_currency": 0,
        "usd": 0
    },
    "floor_price_in_usd_24h_percentage_change": 6.77711,
    "floor_price_24h_percentage_change": {
        "usd": 6.777108622989593,
        "native_currency": 0
    },
    "market_cap_24h_percentage_change": {
        "usd": 6.777108622989682,
        "native_currency": 0
    },
    "volume_24h_percentage_change": {
        "usd": 0,
        "native_currency": 0
    },
    "number_of_unique_addresses": 961,
    "number_of_unique_addresses_24h_percentage_change": 0,
    "volume_in_usd_24h_percentage_change": 0,
    "total_supply": 12268,
    "one_day_sales": 0,
    "one_day_sales_24h_percentage_change": 0,
    "one_day_average_sale_price": 0,
    "one_day_average_sale_price_24h_percentage_change": 0,
    "links": {
        "homepage": "https://www.cometh.io",
        "twitter": "https://twitter.com/MUSTCometh",
        "discord": ""
    },
    "floor_price_7d_percentage_change": {
        "usd": -5.821827963552815,
        "native_currency": -12.5
    },
    "floor_price_14d_percentage_change": {
        "usd": 206671.97680597243,
        "native_currency": 193927.2857800174
    },
    "floor_price_30d_percentage_change": {
        "usd": 179756.829513247,
        "native_currency": 158113.54307928757
    },
    "floor_price_60d_percentage_change": {
        "usd": 153477.00589033857,
        "native_currency": 116566.66666666667
    },
    "floor_price_1y_percentage_change": {
        "usd": 95582.18773944967,
        "native_currency": 49899.99999999999
    },
    "explorers": [
        {
            "name": "Etherscan",
            "link": "https://etherscan.io/token/0xbcd4f1ecff4318e7a0c791c7728f3830db506c71"
        },
        {
            "name": "Ethplorer",
            "link": "https://ethplorer.io/address/0xbcd4f1ecff4318e7a0c791c7728f3830db506c71"
        }
    ]
}

bored_ape_yacht_club_response = {
    "id": "bored-ape-yacht-club",
    "contract_address": "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d",
    "asset_platform_id": "ethereum",
    "name": "Bored Ape Yacht Club",
    "symbol": "BAYC",
    "image": {
        "small": "https://assets.coingecko.com/nft_contracts/images/20/small/bored-ape-yacht-club.png?1629268335"
    },
    "description": "<h3>What Is the Bored Ape Yacht Club NFT Collection?</h3>\r\n\r\n<p>The Bored Ape Yacht Club is a "
                   "collection of 10,000 unique Bored Ape NFTs, which showcase a series of apes with different "
                   "characteristics and expressions.</p>\r\n\r\n<p>Often the face of NFTs, the BAYC collection is one "
                   "of the most well-known NFT collections, with many celebrities holding the collection. Some of "
                   "these celebrities include Justin Bieber, Eminem, Serena Williams, Stephen Curry, "
                   "Shaquille O&rsquo;Neal, and Jimmy Fallon. Celebrities and investors were not the only ones "
                   "interested in the collection, even big corporate companies like Adidas purchased their own "
                   "Ape.</p>\r\n\r\n<p>Launched in April 2021, the project was available for mint at 0.08 ETH and was "
                   "sold out within 12 hours. Less than 2 years later, "
                   "the <a href=\"https://www.coingecko.com/research/publications/10-most-expensive-nfts-ever-sold\" "
                   "target=\"_blank\">most expensive ape</a> was sold at an astounding 3.4 Million "
                   "USD.</p>\r\n\r\n<h3>Who Is the Team Behind BAYC?</h3>\r\n\r\n<p>The NFT project was created by "
                   "Yuga Labs, a team of four individuals who preferred to use their online pseudonyms and only later "
                   "revealed their identities to the public. The team consists of Greg Solana (<a "
                   "href=\"https://twitter.com/CryptoGarga\" rel=\"nofollow noopener\" "
                   "target=\"_blank\">Gargamel</a>), Wyle Aronow (<a href=\"https://twitter.com/GordonGoner\" "
                   "rel=\"nofollow noopener\" target=\"_blank\">Gordon Goner</a>), Kerem (<a "
                   "href=\"https://twitter.com/TomatoBAYC\" rel=\"nofollow noopener\" target=\"_blank\">Emperor "
                   "Tomato Ketchup</a>), and Zesham (<a "
                   "href=\"https://twitter.com/SassBAYC?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm"
                   "%5E1491151597682180096%7Ctwgr%5E%7Ctwcon%5Es1_&amp;ref_url=https%3A%2F%2Fwww.cnet.com%2Fhow-to"
                   "%2Fbored-ape-yacht-club-nfts-everything-you-need-to-know%2F\" rel=\"nofollow noopener\" "
                   "target=\"_blank\">No Sass</a>).</p>\r\n\r\n<p>The artists that designed the BAYC collection are "
                   "<a href=\"https://www.allseeingseneca.com/\" rel=\"nofollow noopener\" "
                   "target=\"_blank\">Seneca</a>, Thomas Dagley, Migwashere, and other artists who, to this day, "
                   "choose to remain anonymous.</p>\r\n\r\n<p>In 2022, the team behind BAYC, Yuga Labs, also acquired "
                   "2 popular NFT collections &ndash; <a href=\"https://www.coingecko.com/en/nft/cryptopunks\" "
                   "target=\"_blank\">CryptoPunks</a> and <a href=\"https://www.coingecko.com/en/nft/meebits\" "
                   "target=\"_blank\">Meebits</a>, establishing themselves as big players in the NFT "
                   "space.</p>\r\n\r\n<h3>What Is the Utility of the BAYC Collection?</h3>\r\n\r\n<p>Being a holder "
                   "of the BAYC collection doubles as a membership card and grants exclusive access to holders. "
                   "Holding an Ape also allows the owners commercial and branding rights to their "
                   "NFTs.</p>\r\n\r\n<p>BAYC holders are granted exclusive access to &lsquo;THE BATHROOM&rsquo; and a "
                   "private Discord server. &lsquo;THE BATHROOM&rsquo; is a collaborative community board where "
                   "holders are able to draw pixels at intervals of 15 minutes. The Discord server allows BAYC "
                   "holders to interact with other holders and get access to new features.</p>\r\n\r\n<p>BAYC holders "
                   "are also granted access to the Yuga Lab&rsquo;s projects. This will include other NFT collections "
                   "and the BAYC metaverse (Otherside).</p>\r\n\r\n<h3>The Bored Ape Yacht Club "
                   "Ecosystem</h3>\r\n\r\n<p>As part of the <a "
                   "href=\"https://www.coingecko.com/learn/what-is-apecoin-ape-ecosystem\" target=\"_blank\">BAYC "
                   "ecosystem</a>, the team also launched its own native token, "
                   "<a href=\"https://www.coingecko.com/en/coins/apecoin\" target=\"_blank\">Apecoin</a>, "
                   "several spin-off NFT collections, and its own <a "
                   "href=\"https://www.coingecko.com/learn/what-is-metaverse-crypto-blockchain-nft-game\" "
                   "target=\"_blank\">metaverse</a>.</p>\r\n\r\n<p>Launched in March 2022, Yuga Labs released their "
                   "native token APE, which functions as a governance token. This ERC-20 token APE allows holders to "
                   "execute transactions, make governing decisions, and participate in the ecosystem. During the "
                   "launch, a portion of the token supply was airdropped to BAYC and MAYC owners.</p>\r\n\r\n<p>Yuga "
                   "Labs also launched spin-off collections such as the <a "
                   "href=\"https://www.coingecko.com/en/nft/mutant-ape-yacht-club\" target=\"_blank\">Mutant Ape "
                   "Yacht Club</a> (MAYC) and the <a href=\"https://www.coingecko.com/en/nft/bored-ape-kennel-club\" "
                   "target=\"_blank\">Bored Ape Kennel Club</a> (BAKC). In August 2021, Yuga Labs airdropped BAYC "
                   "holders a &ldquo;mutant serum&rdquo;. With the serum, BAYC holders were able to mutate or mint "
                   "their own Bored Ape into a Mutant Ape.</p>\r\n\r\n<p>In July 2021, BAYC holders were airdropped "
                   "the BAKC collection. The BAKC collection functions as a companion collection in a bid to reward "
                   "BAYC holders.</p>\r\n\r\n<p>The BAYC ecosystem also consists of the <a "
                   "href=\"https://www.coingecko.com/en/nft/otherdeed-for-otherside\" target=\"_blank\">Otherside "
                   "Metaverse</a>. While the metaverse is still currently under development, when completed, "
                   "the metaverse will be a virtual world where their NFTs can be used as playable "
                   "characters.</p>\r\n\r\n<p>In September 2023, Yuga Labs announced the launch of a new game, "
                   "Legend of the Mara (LotM), a collection-based 2D strategy game. The game is a sub-universe within "
                   "the broader Otherside metaverse game.</p>\r\n",
    "native_currency": "ethereum",
    "native_currency_symbol": "ETH",
    "floor_price": {
        "native_currency": 26.73,
        "usd": 63482
    },
    "market_cap": {
        "native_currency": 267290,
        "usd": 634696668
    },
    "volume_24h": {
        "native_currency": 1920.81,
        "usd": 4561088
    },
    "floor_price_in_usd_24h_percentage_change": 1.82152,
    "floor_price_24h_percentage_change": {
        "usd": 1.8215180161798121,
        "native_currency": -3.0748510339786965
    },
    "market_cap_24h_percentage_change": {
        "usd": 1.8215180161797808,
        "native_currency": -3.076634584731722
    },
    "volume_24h_percentage_change": {
        "usd": 128.11794839466012,
        "native_currency": 114.12878060102341
    },
    "number_of_unique_addresses": 5612,
    "number_of_unique_addresses_24h_percentage_change": -0.05343,
    "volume_in_usd_24h_percentage_change": 128.11795,
    "total_supply": 9998,
    "one_day_sales": 71,
    "one_day_sales_24h_percentage_change": 115.151515151515,
    "one_day_average_sale_price": 27.053661971830987,
    "one_day_average_sale_price_24h_percentage_change": -0.475355495298981,
    "links": {
        "homepage": "https://www.boredapeyachtclub.com/",
        "twitter": "https://twitter.com/BoredApeYC",
        "discord": "https://discord.gg/3P5K3dzgdB"
    },
    "floor_price_7d_percentage_change": {
        "usd": 9.91237518522501,
        "native_currency": 2.248053855766616
    },
    "floor_price_14d_percentage_change": {
        "usd": -2.425603069209463,
        "native_currency": -8.268209962741853
    },
    "floor_price_30d_percentage_change": {
        "usd": 1.5003408749169267,
        "native_currency": -10.554676006361822
    },
    "floor_price_60d_percentage_change": {
        "usd": 19.218112364437715,
        "native_currency": -9.301765135582132
    },
    "floor_price_1y_percentage_change": {
        "usd": -26.469905638004665,
        "native_currency": -61.489033580440044
    },
    "explorers": [
        {
            "name": "Etherscan",
            "link": "https://etherscan.io/token/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"
        },
        {
            "name": "Ethplorer",
            "link": "https://ethplorer.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"
        }
    ]
}

yuliorigingenone_response = {
    "id": "yuliorigingenone",
    "contract_address": "0x735c4a681f1649f5eee8aac871aa1d89ff056217",
    "asset_platform_id": "binance-smart-chain",
    "name": "YuliOriginGenOne",
    "symbol": "YOG1",
    "image": {
        "small": "https://assets.coingecko.com/nft_contracts/images/2330/small/yuliorigingenone.jpg?1671503645"
    },
    "description": "Yuliverse is the World’s very First Parallel Reality Gaming Metaverse on BSC chain, Inspired by "
                   "Pokemon Go & Tinder. Growing new and meaningful friendships at the same time earning in Yuliverse "
                   "with ease, by just moving around in your neighbourhood! YuliOriginGenOne, the first generation of "
                   "the Yuliverse NFT collection. Representing your first step into the Yuliverse.",
    "native_currency": "binancecoin",
    "native_currency_symbol": "BNB",
    "floor_price": {
        "native_currency": 360,
        "usd": 113306
    },
    "market_cap": {
        "native_currency": 1870200,
        "usd": 588625232
    },
    "volume_24h": {
        "native_currency": 0.443692,
        "usd": 139.65
    },
    "floor_price_in_usd_24h_percentage_change": 5.55547,
    "floor_price_24h_percentage_change": {
        "usd": 5.555467404011084,
        "native_currency": 0
    },
    "market_cap_24h_percentage_change": {
        "usd": 5.555467404011235,
        "native_currency": 0
    },
    "volume_24h_percentage_change": {
        "usd": 168.17913596295847,
        "native_currency": 151.60336150456192
    },
    "number_of_unique_addresses": 2573,
    "number_of_unique_addresses_24h_percentage_change": 0.11673,
    "volume_in_usd_24h_percentage_change": 168.17914,
    "total_supply": 5195,
    "one_day_sales": 8,
    "one_day_sales_24h_percentage_change": 60,
    "one_day_average_sale_price": 0.05546144664148025,
    "one_day_average_sale_price_24h_percentage_change": 57.2521009403512,
    "links": {
        "homepage": "https://www.yuliverse.com",
        "twitter": "https://twitter.com/",
        "discord": "https://discord.gg/yuliverseofficial"
    },
    "floor_price_7d_percentage_change": {
        "usd": 260426.3517123858,
        "native_currency": 211664.70588235292
    },
    "floor_price_14d_percentage_change": {
        "usd": 2060161.5554774594,
        "native_currency": 1685686.624423851
    },
    "floor_price_30d_percentage_change": {
        "usd": 2259894.538554392,
        "native_currency": 1685686.624423851
    },
    "floor_price_60d_percentage_change": {
        "usd": 2335492.559615939,
        "native_currency": 1685686.624423851
    },
    "floor_price_1y_percentage_change": {
        "usd": 572257.9130502722,
        "native_currency": 448033.30264453386
    },
    "explorers": [
        {
            "name": "Bscscan",
            "link": "https://bscscan.com/token/0x735c4a681f1649f5eee8aac871aa1d89ff056217"
        },
        {
            "name": "Binplorer",
            "link": "https://binplorer.com/address/0x735c4a681f1649f5eee8aac871aa1d89ff056217"
        }
    ]
}
